name: Windows build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  TARGET: FightClubGame
  VCPKG_ROOT: $GITHUB_WORKSPACE/vcpkg

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download VCPKG
      run: ./Automation/downloadVCPKG.bat

    - name: Install packages
      run: ./Automation/installPackages.bat


    - name: Configure CMake
      run: ./generate_project_files.bat

    - name: Build
      run: ./build_release.bat

    - name: Test
      run: ./test.bat

    
